# Конфигурация Dependabot для автоматического обновления зависимостей
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Обновления Python зависимостей через Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 10
    reviewers:
      - "asmazaev"
    assignees:
      - "asmazaev"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Игнорируем major обновления для критических зависимостей
      - dependency-name: "tensorflow"
        update-types: ["version-update:semver-major"]
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ray"
        update-types: ["version-update:semver-major"]

  # Обновления GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "asmazaev"
    assignees:
      - "asmazaev"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"

  # Обновления Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 3
    reviewers:
      - "asmazaev"
    assignees:
      - "asmazaev"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"