version: 2


build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - pip install poetry>=1.6
      - poetry config virtualenvs.create false
      - poetry install --with dev

sphinx:
  configuration: docs/conf.py
