site_name: TensorAeroSpace 
site_description: Open source deep learning framework for aerospace objects
repo_url: https://github.com/TensorAeroSpace/TensorAeroSpace
repo_name: TensorAeroSpace/TensorAeroSpace
docs_dir: docs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
          options:
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            members_order: source
            docstring_style: google
            heading_level: 2
            show_source: false
            extensions: []
  - autorefs:
      resolve_closest: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
          nav:
            - Home: index.md
            - User Guide:
              - Installation: guide/installation.md
              - Unity Environment: guide/unity_env.md
            - Aerospace Models:
              - F16: model/f16.md
              - B747: 
                - Classic State-Space: model/b747.md
                - Normalized State-Space: model/b747_imporove.md
              - EVL: model/evl.md
              - Typical Rocket: model/typical_rocket.md
              - ComSat: model/comsat.md
              - F4C: model/f4c.md
              - GeoSat: model/geosat.md
              - UAV: model/uav.md
              - X15: model/x15.md
              - LSU: model/lsu.md
              - SUAV: model/suav.md
              - Unity Environment: model/unity_env.md
              
            - Agents:
              - IHDP:
                - Description: agent/ihdp.md
                - Example with LinearLongitudinalF16‑v0: agent/ihdp/example.md
              - MPC: agent/mpc.md
              - DQN: agent/dqn.md
              - A3C: agent/a3c.md
              - A2C-NARX: agent/a2c_narx.md
              - PPO: agent/ppo.md
              - SAC: agent/sac.md
              - DDPG: agent/ddpg.md
              - GAIL: agent/gail.md
              - Optimization: optimization/optuna_based.md
              - Benchmark:
                - Overview: benchmark/bench.md
                - Metrics: benchmark/metrics.md
              - Signals: signals/signals.md
            - Examples:
              - Environments: example/enviroment/gymnasium.md
              - IHDP: example/agent/ihdp/example_ihdp.md
              - SAC F16: example/agent/sac/example-sac-f16.md
              - SAC B747: example/agent/sac/example-sac-b747.md
              - Optimization: example/optimization/example_optimization.md
              - A2C-NARX: example/agent/a2c_narx/example-narx.md
              - MPC: example/agent/mpc/example_mpc.md
              - MPC Transformers: example/agent/mpc/example_transformers.md
              - IHDP Failure: example/failure/ihdp-failure.md
              - Simulink:
                - Simulink to Python: example/simulink/sim_pyth.md
                - Your Simulink: example/simulink/your_sim.md
              - Unity:
                - Unity with DQN: example/enviroment/unity_example.md
              - Simintech:
                - Simintech: example/simintech/simintech.md
                - Simintech to Python: example/simintech/simintechToPython.md
            - Lessons:
              - Theory:
                - "Lesson 1 — Introduction and State-Space": lesson/base/tutor_1.md
                - "Lesson 2 — Controllability and Observability": lesson/base/tutor_2.md
                - "Lesson 3 — Stability of Control Systems": lesson/base/tutor_3.md
                - "Lesson 4 — Fundamentals of Flight Dynamics": lesson/base/tutor_4.md
                - "Lesson 5 — Pole Placement Method": lesson/base/tutor_5.md
                - "Lesson 6 — Observers and the Separation Principle": lesson/base/tutor_6.md
                - "Lesson 7 — Practice: Longitudinal Stabilization": lesson/base/tutor_7.md
              - XFLR5:
                - Introduction: lesson/0intro.md
                - Airfoil Analysis: lesson/1analysis_airfoil.md
                - Plane Aero Analysis: lesson/2analysis_plane_aero.md
                - Plane Static Analysis: lesson/3analysis_plane_static.md
                - MATLAB Script: lesson/4matlabscript.md
                - Simulink Model: lesson/5simulinkmodel.md
                - DLL Generation: lesson/6dllgen.md
        - locale: ru
          name: Русский
          build: true
          nav:
            - Главная: index.md
            - Инструкции:
              - Установка: guide/installation.md
              - Unity-окружение: guide/unity_env.md
            - Объекты управления:
              - F16: model/f16.md
              - B747: 
                - Пространство состояний: model/b747.md
                - Нормализованное управление: model/b747_imporove.md
              - EVL: model/evl.md
              - Typical Rocket: model/typical_rocket.md
              - ComSat: model/comsat.md
              - F4C: model/f4c.md
              - GeoSat: model/geosat.md
              - UAV: model/uav.md
              - X15: model/x15.md
              - LSU: model/lsu.md
              - SUAV: model/suav.md
              - Unity окружение: model/unity_env.md
            - Алгоритмы управления:
              - IHDP:
                - Описание: agent/ihdp.md
                - Пример LinearLongitudinalF16‑v0: agent/ihdp/example.md
              - MPC: agent/mpc.md
              - DQN: agent/dqn.md
              - A3C: agent/a3c.md
              - A2C-NARX: agent/a2c_narx.md
              - PPO: agent/ppo.md
              - SAC: agent/sac.md
              - DDPG: agent/ddpg.md
              - GAIL: agent/gail.md
              - Оптимизация: optimization/optuna_based.md
              - Бенчмаркинг:
                - Обзор: benchmark/bench.md
                - Метрики: benchmark/metrics.md
              - Сигналы: signals/signals.md
            - Примеры:
              - Окружения: example/enviroment/gymnasium.md
              - IHDP: example/agent/ihdp/example_ihdp.md
              - SAC F16: example/agent/sac/example-sac-f16.md
              - Оптимизация: example/optimization/example_optimization.md
              - A2C-NARX: example/agent/a2c_narx/example-narx.md
              - MPC: example/agent/mpc/example_mpc.md
              - MPC Transformers: example/agent/mpc/example_transformers.md
              - IHDP отказы: example/failure/ihdp-failure.md
              - Simulink:
                - Simulink в Python: example/simulink/sim_pyth.md
                - Ваш Simulink: example/simulink/your_sim.md
              - Unity:
                - Unity с DQN: example/enviroment/unity_example.md
              - Simintech:
                - Simintech: example/simintech/simintech.md
                - Simintech в Python: example/simintech/simintechToPython.md
            - Уроки:
              - Теория:
                - "Урок 1 — Введение и пространство состояний": lesson/base/tutor_1.md
                - "Урок 2 — Управляемость и наблюдаемость": lesson/base/tutor_2.md
                - "Урок 3 — Устойчивость систем управления": lesson/base/tutor_3.md
                - "Урок 4 — Основы динамики полета": lesson/base/tutor_4.md
                - "Урок 5 — Метод размещения полюсов": lesson/base/tutor_5.md
                - "Урок 6 — Наблюдатели и принцип разделения": lesson/base/tutor_6.md
                - "Урок 7 — Практика: стабилизация продольного движения": lesson/base/tutor_7.md
              - XFLR5:
                - Введение: lesson/0intro.md
                - Анализ профиля крыла: lesson/1analysis_airfoil.md
                - Аэродинамический анализ самолёта: lesson/2analysis_plane_aero.md
                - Статический анализ самолёта: lesson/3analysis_plane_static.md
                - Скрипт MATLAB: lesson/4matlabscript.md
                - Модель Simulink: lesson/5simulinkmodel.md
                - Генерация DLL: lesson/6dllgen.md
      reconfigure_material: true



theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs
    - content.code.copy
  logo: logo.png
  favicon: logo.png

extra:
  alternate:
    - name: English
      lang: en
      link: /en/
    - name: Русский
      lang: ru
      link: /ru/
  static:
    - assets
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
      guess_lang: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - def_list
