function [ xs ] = F16State_vec2struct( xv )
xnames = {'alpha', 'beta', ...
          'wx', 'wy', 'wz', ...
          'gamma', 'psi', 'theta', ...
          'stab', 'dstab', ...
          'ail', 'dail', ...
          'dir', 'ddir'};
xs = cell2struct(con2seq(xv')', xnames);
end

