name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies and create virtual environment
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run tests
      run: |
        poetry run pytest
